TrajectoryPlannerROS:
    max_vel_x: 0.6
    min_vel_x: 0.1
    max_vel_theta: 1.0
    min_in_place_vel_theta: -0.3

    acc_lim_theta: 2.5
    acc_lim_x: 2
    acc_lim_y: 0
    holonomic_robot: false

    sim_time: 5
    controller_frequency: 6.0
    vx_samples: 15
    vtheta_samples: 30
    yaw_goal_tolerence: 0.05
    xy_goal_tolerence: 0.1






