map_type: costmap

obstacle_range: 2.5 #updates obstacles within 2 meters
raytrace_range: 3.0 #clears space up to three meters

#changed from 0.5 -> 0.2 (default is 0.1 in ROS)
transform_tolerance: 0.6

robot_radius: 0.3 
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}

