local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10
   publish_frequency: 5
   width: 7
   height: 7
   resolution: 0.05
   static_map: false
   rolling_window: true

   footprint_padding: 0.1

