local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 5.0
   width: 6.0
   height: 6.0
   resolution: 0.05
   static_map: false
   rolling_window: true

   footprint_padding: 0.1
   transform_tolerence: 15
   robot_radius: 0.3 
   planner_frequency: 2
   controller_frequency: 10
